### ISSUE TITLE
Archive the 2015 content

### ISSUE THREAD

**Issue by karlgroves** [ThePacielloGroup/inclusivedesign24.org#2]

**Comment by patrickhlauke** [comment]
btw...just in case it's not clear: there's no automatic publication from github to live site. needs to be manually done with FTP. happy to get that properly implemented here (e.g. hosting under gh-pages with relevant CNAME etc)

**Comment by karlgroves** [comment]
Awesome. I think that makes a ton of sense.  I'd added `grunt-ftp-deploy` to the new grunfile but I think perhaps hosting it right on gh-pages is better. I'll remove the `grunt-ftp-deploy` dep and open a new issue for you to do the gh-pages stuff.
