### ISSUE TITLE
Make it possible to deploy to gh-pages

### ISSUE THREAD

**Issue by karlgroves** [ThePacielloGroup/inclusivedesign24.org#4]

**Comment by MichielBijl** [comment]
What is needed for this? I figure you can just publish a index.html to a gh-pages branch and be done with it?

**Comment by karlgroves** [comment]
We need the CNAME record for `inclusivedesign24.org` to point to the gh-pages url. Doing so requires the guy-with-the-keys (that's @patrickhlauke) to make the change.

**Comment by MichielBijl** [comment]
Ah okay, so gh-pages already work themselves? Just that they aren't linked to the domain?

**Comment by patrickhlauke** [comment]
> Doing so requires the guy-with-the-keys (that's @patrickhlauke) to make the change.

actually, it's the girl with the keys @LjWatson ... I don't have any power over the URL/DNS/etc

**Comment by karlgroves** [comment]
Ah, OK.  Let's leave things how they are now as we make adjustments for 2016 and then flip the switch when we're ready.

**Comment by LjWatson** [comment]
@patrickhlauke @karlgroves I no longer have the keys to the kingdom. Transferred the domain to TPG a while ago.

**Comment by patrickhlauke** [comment]
@LjWatson then Mike will do it...in seriousness, I'll sort it out once we've done the update and think it's good to go

**Comment by patrickhlauke** [comment]
Closing this for now, as there's some question mark over whether or not we want to host on GH and deal with cloudflare integration for the SSL cert etc.
